/**
 * PayrollStream ABI — generated from Foundry out/PayrollStream.sol/PayrollStream.json
 * Do not edit by hand. Re-generate by running: forge build
 */
export const PAYROLL_STREAM_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "admin", type: "address", internalType: "address" },
      { name: "feeRecipient_", type: "address", internalType: "address" },
      { name: "receiptNFT_", type: "address", internalType: "address" },
      {
        name: "emergencySigners",
        type: "address[]",
        internalType: "address[]",
      },
      { name: "emergencyThreshold_", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ADMIN_TRANSFER_DELAY",
    inputs: [],
    outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ARBITER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_DENOMINATOR",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_CANCEL_GRACE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_MAX_PAUSE_DURATION",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_MAX_STREAMS_PER_EMPLOYER",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_MAX_STREAM_DURATION",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_MIN_STREAM_DURATION",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_WITHDRAWAL_COOLDOWN",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "EMERGENCY_SIGNER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_BATCH_CANCEL",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_BATCH_CREATE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_BATCH_WITHDRAW",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_EARLY_CANCEL_FEE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PAUSER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "acceptDefaultAdminTransfer",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "activeStreamCount",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchCancel",
    inputs: [
      { name: "streamIds", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchCreate",
    inputs: [
      {
        name: "params",
        type: "tuple[]",
        internalType: "struct PayrollStream.StreamParams[]",
        components: [
          { name: "worker", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "totalAmount", type: "uint256", internalType: "uint256" },
          { name: "startTs", type: "uint256", internalType: "uint256" },
          { name: "endTs", type: "uint256", internalType: "uint256" },
          { name: "cliffTs", type: "uint256", internalType: "uint256" },
          { name: "metadataHash", type: "bytes32", internalType: "bytes32" },
        ],
      },
    ],
    outputs: [{ name: "ids", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchWithdraw",
    inputs: [
      { name: "streamIds", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "beginDefaultAdminTransfer",
    inputs: [{ name: "newAdmin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "blacklisted",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelDefaultAdminTransfer",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelGracePeriod",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "changeDefaultAdminDelay",
    inputs: [{ name: "newDelay", type: "uint48", internalType: "uint48" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createStream",
    inputs: [
      {
        name: "p",
        type: "tuple",
        internalType: "struct PayrollStream.StreamParams",
        components: [
          { name: "worker", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "totalAmount", type: "uint256", internalType: "uint256" },
          { name: "startTs", type: "uint256", internalType: "uint256" },
          { name: "endTs", type: "uint256", internalType: "uint256" },
          { name: "cliffTs", type: "uint256", internalType: "uint256" },
          { name: "metadataHash", type: "bytes32", internalType: "bytes32" },
        ],
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createStreamFor",
    inputs: [
      { name: "employer", type: "address", internalType: "address" },
      {
        name: "p",
        type: "tuple",
        internalType: "struct PayrollStream.StreamParams",
        components: [
          { name: "worker", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "totalAmount", type: "uint256", internalType: "uint256" },
          { name: "startTs", type: "uint256", internalType: "uint256" },
          { name: "endTs", type: "uint256", internalType: "uint256" },
          { name: "cliffTs", type: "uint256", internalType: "uint256" },
          { name: "metadataHash", type: "bytes32", internalType: "bytes32" },
        ],
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createStreamWithPermit2",
    inputs: [
      {
        name: "p",
        type: "tuple",
        internalType: "struct PayrollStream.StreamParams",
        components: [
          { name: "worker", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "totalAmount", type: "uint256", internalType: "uint256" },
          { name: "startTs", type: "uint256", internalType: "uint256" },
          { name: "endTs", type: "uint256", internalType: "uint256" },
          { name: "cliffTs", type: "uint256", internalType: "uint256" },
          { name: "metadataHash", type: "bytes32", internalType: "bytes32" },
        ],
      },
      { name: "nonce", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "defaultAdmin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultAdminDelay",
    inputs: [],
    outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultAdminDelayIncreaseWait",
    inputs: [],
    outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "disputes",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "raisedBy", type: "address", internalType: "address" },
      { name: "raisedAt", type: "uint256", internalType: "uint256" },
      {
        name: "workerVestedSnapshot",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "reason", type: "string", internalType: "string" },
      {
        name: "outcome",
        type: "uint8",
        internalType: "enum PayrollStream.DisputeOutcome",
      },
      { name: "workerShareBps", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "earlyCancelFeeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "emergencyThreshold",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "emergencyVoteCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "emergencyVotePause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "emergencyVoteRound",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "emergencyVotedRound",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "employerStreamCap",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "extendStream",
    inputs: [
      { name: "streamId", type: "uint256", internalType: "uint256" },
      { name: "newEndTs", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "addedAmount", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "finalizeCancel",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "forceResume",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getDispute",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct PayrollStream.Dispute",
        components: [
          { name: "raisedBy", type: "address", internalType: "address" },
          { name: "raisedAt", type: "uint256", internalType: "uint256" },
          {
            name: "workerVestedSnapshot",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "reason", type: "string", internalType: "string" },
          {
            name: "outcome",
            type: "uint8",
            internalType: "enum PayrollStream.DisputeOutcome",
          },
          { name: "workerShareBps", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getReceiptTokenId",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "tokenId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoleAdmin",
    inputs: [{ name: "role", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStream",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct PayrollStream.Stream",
        components: [
          { name: "employer", type: "address", internalType: "address" },
          { name: "worker", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "totalAmount", type: "uint256", internalType: "uint256" },
          { name: "withdrawnAmount", type: "uint256", internalType: "uint256" },
          { name: "startTs", type: "uint256", internalType: "uint256" },
          { name: "endTs", type: "uint256", internalType: "uint256" },
          { name: "cliffTs", type: "uint256", internalType: "uint256" },
          { name: "pausedAt", type: "uint256", internalType: "uint256" },
          {
            name: "totalPausedDuration",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "cancelRequestedAt",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "closedAt", type: "uint256", internalType: "uint256" },
          { name: "metadataHash", type: "bytes32", internalType: "bytes32" },
          {
            name: "status",
            type: "uint8",
            internalType: "enum PayrollStream.Status",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStreamsByEmployer",
    inputs: [{ name: "employer", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStreamsByWorker",
    inputs: [{ name: "worker", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "grantRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastWithdrawalTs",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxPauseDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxStreamDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxStreamsPerEmployer",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minStreamDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextStreamId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "operatorApproval",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pauseStream",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingDefaultAdmin",
    inputs: [],
    outputs: [
      { name: "newAdmin", type: "address", internalType: "address" },
      { name: "schedule", type: "uint48", internalType: "uint48" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingDefaultAdminDelay",
    inputs: [],
    outputs: [
      { name: "newDelay", type: "uint48", internalType: "uint48" },
      { name: "schedule", type: "uint48", internalType: "uint48" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "raiseDispute",
    inputs: [
      { name: "streamId", type: "uint256", internalType: "uint256" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "receiptNFT",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IProofOfIncome" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "receiptTokenIdPlus1",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestCancel",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resetEmergencyVotes",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveDispute",
    inputs: [
      { name: "streamId", type: "uint256", internalType: "uint256" },
      {
        name: "outcome",
        type: "uint8",
        internalType: "enum PayrollStream.DisputeOutcome",
      },
      { name: "workerShareBps", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resumeStream",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rollbackDefaultAdminDelay",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setBlacklisted",
    inputs: [
      { name: "target", type: "address", internalType: "address" },
      { name: "flag", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCancelGracePeriod",
    inputs: [{ name: "v", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEarlyCancelFee",
    inputs: [
      { name: "bps", type: "uint256", internalType: "uint256" },
      { name: "recipient", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEmergencyThreshold",
    inputs: [{ name: "t", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEmployerStreamCap",
    inputs: [
      { name: "employer", type: "address", internalType: "address" },
      { name: "cap", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxPauseDuration",
    inputs: [{ name: "v", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxStreamDuration",
    inputs: [{ name: "v", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxStreamsPerEmployer",
    inputs: [{ name: "v", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinStreamDuration",
    inputs: [{ name: "v", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOperator",
    inputs: [
      { name: "operator", type: "address", internalType: "address" },
      { name: "approved", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setWithdrawalCooldown",
    inputs: [{ name: "v", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "streamRatePerSecond",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "streams",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "employer", type: "address", internalType: "address" },
      { name: "worker", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "totalAmount", type: "uint256", internalType: "uint256" },
      { name: "withdrawnAmount", type: "uint256", internalType: "uint256" },
      { name: "startTs", type: "uint256", internalType: "uint256" },
      { name: "endTs", type: "uint256", internalType: "uint256" },
      { name: "cliffTs", type: "uint256", internalType: "uint256" },
      { name: "pausedAt", type: "uint256", internalType: "uint256" },
      { name: "totalPausedDuration", type: "uint256", internalType: "uint256" },
      { name: "cancelRequestedAt", type: "uint256", internalType: "uint256" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "closedAt", type: "uint256", internalType: "uint256" },
      { name: "metadataHash", type: "bytes32", internalType: "bytes32" },
      {
        name: "status",
        type: "uint8",
        internalType: "enum PayrollStream.Status",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawCrossChain",
    inputs: [
      { name: "streamId", type: "uint256", internalType: "uint256" },
      { name: "destinationDomain", type: "uint32", internalType: "uint32" },
      { name: "mintRecipient", type: "bytes32", internalType: "bytes32" },
      { name: "maxFee", type: "uint256", internalType: "uint256" },
      { name: "minFinalityThreshold", type: "uint32", internalType: "uint32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawable",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawalCooldown",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "workerBalance",
    inputs: [{ name: "worker", type: "address", internalType: "address" }],
    outputs: [
      { name: "totalWithdrawable", type: "uint256", internalType: "uint256" },
      { name: "totalWithdrawn", type: "uint256", internalType: "uint256" },
      { name: "totalStreaming", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "workerExit",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "BlacklistUpdated",
    inputs: [
      {
        name: "target",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "blacklisted",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CancelRequested",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "gracePeriodEndsAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DefaultAdminDelayChangeCanceled",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "DefaultAdminDelayChangeScheduled",
    inputs: [
      {
        name: "newDelay",
        type: "uint48",
        indexed: false,
        internalType: "uint48",
      },
      {
        name: "effectSchedule",
        type: "uint48",
        indexed: false,
        internalType: "uint48",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DefaultAdminTransferCanceled",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "DefaultAdminTransferScheduled",
    inputs: [
      {
        name: "newAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "acceptSchedule",
        type: "uint48",
        indexed: false,
        internalType: "uint48",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DisputeRaised",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "raisedBy",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DisputeResolved",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "outcome",
        type: "uint8",
        indexed: false,
        internalType: "enum PayrollStream.DisputeOutcome",
      },
      {
        name: "workerAmt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "employerAmt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EmergencyPauseVote",
    inputs: [
      {
        name: "signer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "voteCount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EmergencyVotesReset",
    inputs: [
      {
        name: "newRound",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeeConfigUpdated",
    inputs: [
      { name: "bps", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "recipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OperatorSet",
    inputs: [
      {
        name: "employer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "operator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "approved", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ParamUpdated",
    inputs: [
      { name: "key", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReceiptLinked",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "tokenId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReceiptMintFailed",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleAdminChanged",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "previousAdminRole",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "newAdminRole",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleGranted",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleRevoked",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StreamCancelled",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "workerSettlement",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "employerRefund",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "protocolFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StreamCompleted",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "totalPaid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StreamCreated",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "employer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "worker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "totalAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "startTs",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "endTs",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "cliffTs",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "metadataHash",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StreamExtended",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "newEndTs",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "addedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StreamForceResumed",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "resumedAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StreamPaused",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "pausedAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StreamResumed",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "resumedAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalPausedDuration",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "worker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "withdrawnTotal",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawnCrossChain",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "worker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "destinationDomain",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      {
        name: "mintRecipient",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WorkerExited",
    inputs: [
      {
        name: "streamId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "workerSettlement",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "employerRefund",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
  {
    type: "error",
    name: "AccessControlEnforcedDefaultAdminDelay",
    inputs: [{ name: "schedule", type: "uint48", internalType: "uint48" }],
  },
  { type: "error", name: "AccessControlEnforcedDefaultAdminRules", inputs: [] },
  {
    type: "error",
    name: "AccessControlInvalidDefaultAdmin",
    inputs: [
      { name: "defaultAdmin", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "AccessControlUnauthorizedAccount",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "neededRole", type: "bytes32", internalType: "bytes32" },
    ],
  },
  { type: "error", name: "AlreadyDisputed", inputs: [] },
  { type: "error", name: "AlreadyVoted", inputs: [] },
  {
    type: "error",
    name: "BatchTooLarge",
    inputs: [{ name: "max", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "Blacklisted", inputs: [] },
  {
    type: "error",
    name: "CooldownNotElapsed",
    inputs: [{ name: "availableAt", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "DurationTooLong",
    inputs: [{ name: "max", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "DurationTooShort",
    inputs: [{ name: "min", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  {
    type: "error",
    name: "GracePeriodNotElapsed",
    inputs: [{ name: "endsAt", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "InvalidAmount", inputs: [] },
  { type: "error", name: "InvalidBps", inputs: [] },
  { type: "error", name: "InvalidCliff", inputs: [] },
  { type: "error", name: "InvalidFeeConfig", inputs: [] },
  { type: "error", name: "InvalidThreshold", inputs: [] },
  { type: "error", name: "InvalidTimeRange", inputs: [] },
  { type: "error", name: "InvalidToken", inputs: [] },
  { type: "error", name: "InvalidWorker", inputs: [] },
  { type: "error", name: "NoDispute", inputs: [] },
  { type: "error", name: "NotAuthorized", inputs: [] },
  { type: "error", name: "NotParticipant", inputs: [] },
  { type: "error", name: "NotWorker", inputs: [] },
  { type: "error", name: "NothingToWithdraw", inputs: [] },
  {
    type: "error",
    name: "PauseCapNotElapsed",
    inputs: [{ name: "availableAt", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeCastOverflowedUintDowncast",
    inputs: [
      { name: "bits", type: "uint8", internalType: "uint8" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "StreamNotActive", inputs: [] },
  { type: "error", name: "StreamNotPaused", inputs: [] },
  { type: "error", name: "TokenNotBridgeable", inputs: [] },
  {
    type: "error",
    name: "TooManyStreams",
    inputs: [{ name: "cap", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;
